### ISSUE TITLE
Version 0.3.1 requires Swift 4.2

### ISSUE THREAD

**Issue by Cellane** [skelpo/CSV#2]
Between versions 0.3.0 and 0.3.1, a few changes in the code were introduced that require Swift 4.2 (which was not released yet), such as `Bool.toggle()`.

I think changes that require different Swift version should be done in major versions or at least minor versions, not patch versions, as `swift update` happily fetched the version `0.3.1` as part of the regular update process, which then made the code uncompilable in the current stable version of Xcode/Swift.

**Comment by ml-milan-vit** [comment]
And after downgrading to 0.3.0, I noticed that this version is rather old and can’t decode CSV files properly 😢

**Comment by Cellane** [comment]
And after downgrading to 0.3.0, I noticed that this version is rather old and can’t decode CSV files properly 😢

**Comment by calebkleveter** [comment]
Sorry. Lesson is be carful if you use a beta toolchain or Xcode release 😄. I'll get that fixed up.

**Comment by Cellane** [comment]
No worries! I actually got trapped by the same thing, CSV 0.3.1 was nicely working for me, I committed my work, submitted everything for PR only to have my colleagues wonder why the code is no longer compiling 😅

**Comment by calebkleveter** [comment]
Fixed in release [0.3.2](https://github.com/skelpo/CSV/releases/tag/0.3.2).

**Comment by Cellane** [comment]
You are so awesome! Thank you!
