### ISSUE TITLE
Support for delimiters other than ","?

### ISSUE THREAD

**Issue by daSkier** [skelpo/CSV#6]
I know this package is appropriately titled CSV, but has any thought been given to supporting delimiters other than ","? 

I have a data set that I'm parsing right now that uses "\t" and I've modified the case statement in Parser.swift to be `case 44,9:` rather than  `case 44:`. This isn't a great solution, but for the time being it works. 

If you were interested in supporting this concept I would think abstracting the ascii code away would be a good idea. This could be done by either creating some sort of `Delimiter` enum or adding a `Character` parameter to the parse function.

**Comment by proggeramlug** [comment]
Like it, @calebkleveter can you enable this? Should not be much work.

**Comment by daSkier** [comment]
#7 I put together a quick fork that supports this if you want to take a look.

**Comment by calebkleveter** [comment]
Fixed by https://github.com/skelpo/CSV/pull/7
